// Generated by gencpp from file follow_crop/angle.msg
// DO NOT EDIT!


#ifndef FOLLOW_CROP_MESSAGE_ANGLE_H
#define FOLLOW_CROP_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace follow_crop
{
template <class ContainerAllocator>
struct angle_
{
  typedef angle_<ContainerAllocator> Type;

  angle_()
    : angle(0.0)  {
    }
  angle_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::follow_crop::angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::follow_crop::angle_<ContainerAllocator> const> ConstPtr;

}; // struct angle_

typedef ::follow_crop::angle_<std::allocator<void> > angle;

typedef boost::shared_ptr< ::follow_crop::angle > anglePtr;
typedef boost::shared_ptr< ::follow_crop::angle const> angleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::follow_crop::angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::follow_crop::angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::follow_crop::angle_<ContainerAllocator1> & lhs, const ::follow_crop::angle_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::follow_crop::angle_<ContainerAllocator1> & lhs, const ::follow_crop::angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace follow_crop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::follow_crop::angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::follow_crop::angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow_crop::angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow_crop::angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow_crop::angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow_crop::angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::follow_crop::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::follow_crop::angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::follow_crop::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "follow_crop/angle";
  }

  static const char* value(const ::follow_crop::angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::follow_crop::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
;
  }

  static const char* value(const ::follow_crop::angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::follow_crop::angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::follow_crop::angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::follow_crop::angle_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOLLOW_CROP_MESSAGE_ANGLE_H
