// Generated by gencpp from file follow_crop/pos.msg
// DO NOT EDIT!


#ifndef FOLLOW_CROP_MESSAGE_POS_H
#define FOLLOW_CROP_MESSAGE_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace follow_crop
{
template <class ContainerAllocator>
struct pos_
{
  typedef pos_<ContainerAllocator> Type;

  pos_()
    : direction(0)  {
    }
  pos_(const ContainerAllocator& _alloc)
    : direction(0)  {
  (void)_alloc;
    }



   typedef int32_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::follow_crop::pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::follow_crop::pos_<ContainerAllocator> const> ConstPtr;

}; // struct pos_

typedef ::follow_crop::pos_<std::allocator<void> > pos;

typedef boost::shared_ptr< ::follow_crop::pos > posPtr;
typedef boost::shared_ptr< ::follow_crop::pos const> posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::follow_crop::pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::follow_crop::pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::follow_crop::pos_<ContainerAllocator1> & lhs, const ::follow_crop::pos_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::follow_crop::pos_<ContainerAllocator1> & lhs, const ::follow_crop::pos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace follow_crop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::follow_crop::pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::follow_crop::pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow_crop::pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::follow_crop::pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow_crop::pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::follow_crop::pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::follow_crop::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b685cbe3a2d37c79069d18fc947a4de";
  }

  static const char* value(const ::follow_crop::pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b685cbe3a2d37c7ULL;
  static const uint64_t static_value2 = 0x9069d18fc947a4deULL;
};

template<class ContainerAllocator>
struct DataType< ::follow_crop::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "follow_crop/pos";
  }

  static const char* value(const ::follow_crop::pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::follow_crop::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 direction\n"
;
  }

  static const char* value(const ::follow_crop::pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::follow_crop::pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::follow_crop::pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::follow_crop::pos_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOLLOW_CROP_MESSAGE_POS_H
